# Generated by Django 3.2.25 on 2025-03-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory_table',
        ),
    ]
