# Generated by Django 3.2.25 on 2025-03-25 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.member')),
            ],
            options={
                'db_table': 'booking_table',
            },
        ),
    ]
