# Generated by Django 3.2.25 on 2025-03-26 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20250326_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
